# SPDX-License-Identifier: Apache-2.0
"""
PCA-based KV cache compressor (KVTCCompressor).

Production path uses a pca_bundle generated by the Phase 4 calibration CLI.
Testing path (pca_bundle=None) uses on-the-fly PCA from the input -- explicitly
documented as lower quality and not suitable for production use.

RoPE stripping is the caller's responsibility. Keys passed to compress() must
already have positional encodings removed.
"""

import mlx.core as mx

# MLX lazy graph materialization alias.
# This calls mx.eval(), which forces the MLX compute graph to execute so that
# tensor values are materialised (e.g. before a numpy bridge conversion).
# This is NOT an invocation of Python string evaluation -- it is a tensor
# computation trigger. The alias name documents the intent and avoids confusion
# with unrelated Python builtins.
_mx_materialize = mx.eval


class KVTCCompressor:
    """Compress and decompress a full model KV cache to/from a compact byte blob.

    Compression pipeline:
        1. Exempt sink tokens (first n_sink_tokens) -- stored verbatim.
        2. Exempt sliding window tokens (last sliding_window) -- stored verbatim.
        3. Apply PCA projection to body tokens using pca_bundle (or on-the-fly PCA).
        4. Apply DP-optimised variable-bit quantization per PCA component.
        5. Entropy-code the quantised coefficients with zstandard.

    Decompression is fully self-describing: the blob contains all codebooks,
    group maps, and metadata needed to reconstruct the KV cache without the
    bundle being present in memory (supports SSD cold-storage semantics).
    """

    def __init__(
        self,
        pca_bundle=None,
        n_sink_tokens: int = 4,
        sliding_window: int = 128,
        bits_per_token: float = 4.0,
    ):
        """Initialise the compressor.

        Args:
            pca_bundle: Pre-loaded calibration bundle from Phase 4. When None,
                compress() falls back to on-the-fly PCA (testing only).
            n_sink_tokens: Number of initial tokens exempt from compression.
                Defaults to 4, matching AMCompactor and KVTC-05.
            sliding_window: Number of final tokens exempt from compression.
                Defaults to 128 per KVTC-06.
            bits_per_token: Target bits per token for DP allocation budget.
                Defaults to 4.0.
        """
        self.pca_bundle = pca_bundle
        self.n_sink_tokens = n_sink_tokens
        self.sliding_window = sliding_window
        self.bits_per_token = bits_per_token

    def compress(self, kv_cache: list[tuple[mx.array, mx.array]]) -> bytes:
        """Compress a full model KV cache to a self-describing byte blob.

        Keys must have RoPE stripped by the caller before this call.

        Args:
            kv_cache: List of (keys, values) tuples, one per layer.
                Each tensor has shape [1, n_kv_heads, seq_len, head_dim].

        Returns:
            A self-describing bytes blob (starts with b"KVTC" magic).
        """
        raise NotImplementedError("KVTCCompressor.compress() not yet implemented")

    def decompress(self, blob: bytes) -> list[tuple[mx.array, mx.array]]:
        """Decompress a blob produced by compress() back to KV cache tensors.

        The blob is self-describing: no pca_bundle is required at decompress
        time. This enables SSD storage and retrieval without keeping the bundle
        in memory.

        Args:
            blob: Bytes blob previously produced by compress().

        Returns:
            List of (keys, values) tuples, one per layer, matching the original
            shape [1, n_kv_heads, seq_len, head_dim] in float16.
        """
        raise NotImplementedError("KVTCCompressor.decompress() not yet implemented")
