# SPDX-License-Identifier: Apache-2.0
"""
PCA-based KV cache compressor (KVTCCompressor).

Production path uses a pca_bundle generated by the Phase 4 calibration CLI.
Testing path (pca_bundle=None) uses on-the-fly PCA from the input -- explicitly
documented as lower quality and not suitable for production use.

RoPE stripping is the caller's responsibility. Keys passed to compress() must
already have positional encodings removed.
"""

import struct

import mlx.core as mx
import numpy as np
import zstandard as zstd

from omlx.compression.linalg_utils import svd_f32

# MLX lazy graph materialization alias.
# This calls mx.eval(), which forces the MLX compute graph to execute so that
# tensor values are materialised (e.g. before a numpy bridge conversion).
# This is NOT an invocation of Python string evaluation -- it is a tensor
# computation trigger. The alias name documents the intent and avoids confusion
# with unrelated Python builtins.
_mx_materialize = mx.eval


# ---------------------------------------------------------------------------
# Private compression primitives
# ---------------------------------------------------------------------------


def _split_tokens(tensor, n_sink_tokens: int, sliding_window: int):
    """Split tensor into (sinks, body, window) regions.

    Args:
        tensor: KV tensor with shape [1, n_kv_heads, seq_len, head_dim].
        n_sink_tokens: Number of initial tokens to exempt from compression.
        sliding_window: Number of final tokens to exempt from compression.

    Returns:
        Tuple (sinks, body, window) where body may be zero-length if
        seq_len <= n_sink_tokens + sliding_window.
    """
    seq_len = tensor.shape[2]
    window_start = max(n_sink_tokens, seq_len - sliding_window)
    sinks = tensor[:, :, :n_sink_tokens, :]
    body = tensor[:, :, n_sink_tokens:window_start, :]
    window = tensor[:, :, window_start:, :]
    return sinks, body, window


def _calibrate_onthefly(tensor, n_components: int):
    """Compute on-the-fly PCA basis from a single KV tensor.

    Uses svd_f32 from linalg_utils (direct linalg calls are forbidden outside
    linalg_utils.py) to ensure float32 safety and CPU stream routing.
    This is the testing/fallback path -- lower quality than
    a pre-computed calibration bundle.

    Args:
        tensor: KV tensor with shape [1, n_kv_heads, seq_len, head_dim].
        n_components: Number of PCA components to retain.

    Returns:
        Tuple (basis, mean, singular_values) where:
            basis: mx.array shape [head_dim, n_components]
            mean: mx.array shape [head_dim]
            singular_values: mx.array shape [n_components]
    """
    # Reshape to [n_kv_heads * seq_len, head_dim], cast to float32
    n_kv_heads = tensor.shape[1]
    seq_len = tensor.shape[2]
    head_dim = tensor.shape[3]
    data = tensor.reshape(n_kv_heads * seq_len, head_dim).astype(mx.float32)

    mean = mx.mean(data, axis=0)
    centered = data - mean
    _mx_materialize(centered)

    # svd_f32 returns (U, S, Vt). Using the linalg_utils wrapper is mandatory --
    # callers must not call linalg operations directly outside linalg_utils.py.
    U, S, Vt = svd_f32(centered)
    _mx_materialize(U, S, Vt)

    # basis shape: [head_dim, n_components]
    basis = Vt[:n_components].T
    return basis, mean, S[:n_components]


def _dp_allocate_bits(
    singular_values,
    bits_per_token_budget: float,
    n_tokens: int,
    n_components: int,
    min_bits: int = 1,
    max_bits: int = 8,
) -> np.ndarray:
    """Allocate bit widths per PCA component using a greedy DP strategy.

    Components with higher singular values receive more bits within the overall
    budget. Every component receives at least min_bits.

    Args:
        singular_values: numpy float array [n_components], largest first.
        bits_per_token_budget: Target bits per token (e.g. 4.0).
        n_tokens: Number of body tokens.
        n_components: Number of PCA components.
        min_bits: Minimum bits per component (default 1).
        max_bits: Maximum bits per component (default 8).

    Returns:
        numpy uint8 array of length n_components with values in [min_bits, max_bits].
    """
    total_budget = int(bits_per_token_budget * n_tokens * n_components)
    alloc = np.full(n_components, min_bits, dtype=np.uint8)
    remaining = total_budget - min_bits * n_components

    # Priority order: highest singular value gets extra bits first
    priority = np.argsort(singular_values)[::-1]
    for comp_idx in priority:
        extra = min(int(max_bits) - int(alloc[comp_idx]), remaining)
        if extra <= 0:
            if remaining <= 0:
                break
            continue
        alloc[comp_idx] += extra
        remaining -= extra
        if remaining <= 0:
            break

    return alloc


def _lloyd_codebook(col: np.ndarray, n_bits: int) -> np.ndarray:
    """Build a Lloyd (k-means 1D) codebook for one PCA coefficient column.

    Uses percentile-based centroid initialisation followed by 3 Lloyd iterations.

    Args:
        col: numpy float array of PCA coefficients for one component.
        n_bits: Bit width (1..8); produces 2^n_bits centroids.

    Returns:
        float64 numpy array of shape [2^n_bits] containing the centroids.
    """
    n_levels = 2 ** n_bits
    percentiles = np.linspace(0, 100, n_levels + 1)
    boundaries = np.percentile(col, percentiles)
    centroids = (boundaries[:-1] + boundaries[1:]) / 2.0

    for _ in range(3):
        dists = np.abs(col[:, None] - centroids[None, :])
        indices = np.argmin(dists, axis=1)
        for k in range(n_levels):
            mask = indices == k
            if np.any(mask):
                centroids[k] = col[mask].mean()

    return centroids


def _compress_zstd(data: bytes, level: int = 3) -> bytes:
    """Compress bytes using zstandard at the specified compression level.

    Args:
        data: Raw bytes to compress.
        level: zstd compression level (default 3).

    Returns:
        Compressed bytes.
    """
    return zstd.ZstdCompressor(level=level).compress(data)


def _decompress_zstd(compressed: bytes) -> bytes:
    """Decompress bytes produced by _compress_zstd.

    Args:
        compressed: Bytes produced by _compress_zstd.

    Returns:
        Original uncompressed bytes.
    """
    return zstd.ZstdDecompressor().decompress(compressed)


class KVTCCompressor:
    """Compress and decompress a full model KV cache to/from a compact byte blob.

    Compression pipeline:
        1. Exempt sink tokens (first n_sink_tokens) -- stored verbatim.
        2. Exempt sliding window tokens (last sliding_window) -- stored verbatim.
        3. Apply PCA projection to body tokens using pca_bundle (or on-the-fly PCA).
        4. Apply DP-optimised variable-bit quantization per PCA component.
        5. Entropy-code the quantised coefficients with zstandard.

    Decompression is fully self-describing: the blob contains all codebooks,
    group maps, and metadata needed to reconstruct the KV cache without the
    bundle being present in memory (supports SSD cold-storage semantics).
    """

    def __init__(
        self,
        pca_bundle=None,
        n_sink_tokens: int = 4,
        sliding_window: int = 128,
        bits_per_token: float = 4.0,
    ):
        """Initialise the compressor.

        Args:
            pca_bundle: Pre-loaded calibration bundle from Phase 4. When None,
                compress() falls back to on-the-fly PCA (testing only).
            n_sink_tokens: Number of initial tokens exempt from compression.
                Defaults to 4, matching AMCompactor and KVTC-05.
            sliding_window: Number of final tokens exempt from compression.
                Defaults to 128 per KVTC-06.
            bits_per_token: Target bits per token for DP allocation budget.
                Defaults to 4.0.
        """
        self.pca_bundle = pca_bundle
        self.n_sink_tokens = n_sink_tokens
        self.sliding_window = sliding_window
        self.bits_per_token = bits_per_token

    def compress(self, kv_cache: list[tuple[mx.array, mx.array]]) -> bytes:
        """Compress a full model KV cache to a self-describing byte blob.

        Keys must have RoPE stripped by the caller before this call.

        Args:
            kv_cache: List of (keys, values) tuples, one per layer.
                Each tensor has shape [1, n_kv_heads, seq_len, head_dim].

        Returns:
            A self-describing bytes blob (starts with b"KVTC" magic).
        """
        HEADER_FMT = "!4sIIII"
        header_bytes = struct.pack(
            HEADER_FMT,
            b"KVTC",
            1,
            len(kv_cache),
            self.n_sink_tokens,
            self.sliding_window,
        )
        layer_blobs = []

        for layer_idx, (keys, values) in enumerate(kv_cache):
            sinks_k, body_k, window_k = _split_tokens(
                keys, self.n_sink_tokens, self.sliding_window
            )
            sinks_v, body_v, window_v = _split_tokens(
                values, self.n_sink_tokens, self.sliding_window
            )

            n_kv_heads = keys.shape[1]
            seq_len = keys.shape[2]
            head_dim = keys.shape[3]
            body_len = body_k.shape[2]
            window_len = window_k.shape[2]

            if body_len == 0:
                n_components = 0
                k_basis_bytes = b""
                k_mean_bytes = b""
                v_basis_bytes = b""
                v_mean_bytes = b""
                k_alloc_bytes = b""
                v_alloc_bytes = b""
                k_compressed = b""
                v_compressed = b""
            else:
                # Determine n_components
                if self.pca_bundle is not None:
                    k_basis = self.pca_bundle[layer_idx]["K_basis"]
                    k_mean = self.pca_bundle[layer_idx]["K_mean"]
                    k_sv = self.pca_bundle[layer_idx]["K_sv"]
                    v_basis = self.pca_bundle[layer_idx]["V_basis"]
                    v_mean = self.pca_bundle[layer_idx]["V_mean"]
                    v_sv = self.pca_bundle[layer_idx]["V_sv"]
                    n_components = k_basis.shape[1]
                else:
                    n_components = min(64, head_dim // 2)
                    k_basis, k_mean, k_sv = _calibrate_onthefly(body_k, n_components)
                    v_basis, v_mean, v_sv = _calibrate_onthefly(body_v, n_components)

                # PCA project body
                _mx_materialize(body_k, body_v)
                body_k_f32 = body_k.astype(mx.float32)
                body_v_f32 = body_v.astype(mx.float32)
                k_mean_f32 = k_mean.astype(mx.float32)
                v_mean_f32 = v_mean.astype(mx.float32)
                k_basis_f32 = k_basis.astype(mx.float32)
                v_basis_f32 = v_basis.astype(mx.float32)
                k_coeffs = (body_k_f32 - k_mean_f32) @ k_basis_f32
                v_coeffs = (body_v_f32 - v_mean_f32) @ v_basis_f32
                _mx_materialize(k_coeffs, v_coeffs)
                k_coeffs_np = np.array(k_coeffs).reshape(-1, n_components)
                v_coeffs_np = np.array(v_coeffs).reshape(-1, n_components)

                # DP bit allocation
                if self.pca_bundle is not None:
                    k_bit_alloc = self.pca_bundle[layer_idx]["k_bit_alloc"]
                    v_bit_alloc = self.pca_bundle[layer_idx]["v_bit_alloc"]
                else:
                    k_sv_np = np.array(k_sv)
                    v_sv_np = np.array(v_sv)
                    k_bit_alloc = _dp_allocate_bits(
                        k_sv_np, self.bits_per_token, n_kv_heads * body_len, n_components
                    )
                    v_bit_alloc = _dp_allocate_bits(
                        v_sv_np, self.bits_per_token, n_kv_heads * body_len, n_components
                    )

                # Quantize K via Lloyd + pack to bytes
                k_index_bytes_list = []
                k_codebook_bytes_list = []
                for c in range(n_components):
                    col = k_coeffs_np[:, c]
                    n_bits = int(k_bit_alloc[c])
                    centroids = _lloyd_codebook(col, n_bits)
                    dists = np.abs(col[:, None] - centroids[None, :])
                    indices = np.argmin(dists, axis=1).astype(np.uint8)
                    k_index_bytes_list.append(indices.tobytes())
                    k_codebook_bytes_list.append(centroids.astype(np.float32).tobytes())
                k_index_stream = b"".join(k_index_bytes_list)
                k_codebook_stream = b"".join(k_codebook_bytes_list)
                k_raw = k_index_stream + k_codebook_stream
                k_compressed = _compress_zstd(k_raw)

                # Quantize V via Lloyd + pack to bytes
                v_index_bytes_list = []
                v_codebook_bytes_list = []
                for c in range(n_components):
                    col = v_coeffs_np[:, c]
                    n_bits = int(v_bit_alloc[c])
                    centroids = _lloyd_codebook(col, n_bits)
                    dists = np.abs(col[:, None] - centroids[None, :])
                    indices = np.argmin(dists, axis=1).astype(np.uint8)
                    v_index_bytes_list.append(indices.tobytes())
                    v_codebook_bytes_list.append(centroids.astype(np.float32).tobytes())
                v_index_stream = b"".join(v_index_bytes_list)
                v_codebook_stream = b"".join(v_codebook_bytes_list)
                v_raw = v_index_stream + v_codebook_stream
                v_compressed = _compress_zstd(v_raw)

                # Serialize basis and mean (float32, for self-describing blob)
                _mx_materialize(k_basis, k_mean, v_basis, v_mean)
                k_basis_bytes = np.array(k_basis).astype(np.float32).tobytes()
                k_mean_bytes = np.array(k_mean.reshape(-1)).astype(np.float32).tobytes()
                v_basis_bytes = np.array(v_basis).astype(np.float32).tobytes()
                v_mean_bytes = np.array(v_mean.reshape(-1)).astype(np.float32).tobytes()
                k_alloc_bytes = k_bit_alloc.astype(np.uint8).tobytes()
                v_alloc_bytes = v_bit_alloc.astype(np.uint8).tobytes()

            # Serialize sinks and window verbatim
            _mx_materialize(sinks_k, window_k, sinks_v, window_v)
            sinks_k_bytes = np.array(sinks_k.astype(mx.float16)).tobytes()
            sinks_v_bytes = np.array(sinks_v.astype(mx.float16)).tobytes()
            window_k_bytes = np.array(window_k.astype(mx.float16)).tobytes()
            window_v_bytes = np.array(window_v.astype(mx.float16)).tobytes()

            # Pack per-layer section
            layer_header = struct.pack(
                "!IIIII", layer_idx, n_kv_heads, seq_len, head_dim, n_components
            )
            window_len_packed = struct.pack("!I", window_len)
            k_comp_len_packed = struct.pack("!I", len(k_compressed))
            v_comp_len_packed = struct.pack("!I", len(v_compressed))
            layer_blob = (
                layer_header
                + sinks_k_bytes
                + sinks_v_bytes
                + window_len_packed
                + window_k_bytes
                + window_v_bytes
                + k_comp_len_packed
                + k_compressed
                + v_comp_len_packed
                + v_compressed
                + k_alloc_bytes
                + v_alloc_bytes
                + k_basis_bytes
                + k_mean_bytes
                + v_basis_bytes
                + v_mean_bytes
            )
            layer_blobs.append(layer_blob)

        return header_bytes + b"".join(layer_blobs)

    def decompress(self, blob: bytes) -> list[tuple[mx.array, mx.array]]:
        """Decompress a blob produced by compress() back to KV cache tensors.

        The blob is self-describing: no pca_bundle is required at decompress
        time. This enables SSD storage and retrieval without keeping the bundle
        in memory.

        Args:
            blob: Bytes blob previously produced by compress().

        Returns:
            List of (keys, values) tuples, one per layer, matching the original
            shape [1, n_kv_heads, seq_len, head_dim] in float16.
        """
        raise NotImplementedError("KVTCCompressor.decompress() not yet implemented")
